#!/usr/bin/env sh

##############################
# @jaimecgomezz
#
# Easily run common
# docker-compose commands
#
# requirements:
#   - docker-compose
##############################

USAGE="USAGE: dkc ACTION [CONTAINER...]

Actions:
  -                       Enter interactive mode
  l, list                 List containers
  u, up   [CONTAINER...]  Run all or specified container
  s, stop [CONTAINER...]  Stop all or specified containers
  h, help                 Print this guide
"
print_usage() { echo "$USAGE"; }

run_containers() { docker-compose up -d "$@"; }
stop_containers() { docker-compose stop "$@"; }
list_containers() { docker-compose ps --format json | jq -r '["Container","Status"], ["---------", "------"], (.[] | [.Name,.State]) | @tsv'; }

if [ -z "$1" ]; then
	actions="$(printf "%s\n%s\n%s" "list" "up" "stop")"
	if action="$(echo "$actions" | fzf)"; then
		dkc "$action"
		exit "$?"
	else
		exit 1
	fi
fi

COMMAND="$1"
shift

case "$COMMAND" in
l | list) list_containers ;;
u | up) run_containers "$@" ;;
s | stop) stop_containers "$@" ;;
h | help | *) print_usage ;;
esac
