#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Get entries from Go's dev
# blog as PDF
#
# Requires:
#   - curl
#   - wkhtmltopdf
#   - poppler (pdfunite)
#------------------------ vars
OUTPUT_FILE="blog.pdf"
TEMP_DIR=godevblogtempdir
BLOG_HOST="https://go.dev"
#-----------------------------

USAGE="USAGE: go2pdf [OUTPUT]

OUTPUT
  -         Defaults to blog.pdf
  h, help   Print this guide"
print_usage() { echo "$USAGE"; }

case "$1" in
h | help)
	print_usage
	exit 0
	;;
*) OUTPUT_FILE="${1:-$OUTPUT_FILE}" ;;
esac

if [ -d "$TEMP_DIR" ]; then
	cd "$TEMP_DIR" || exit 1
else
	mkdir "$TEMP_DIR" && cd "$TEMP_DIR" || exit 1
fi

entries=$(
	curl -s "$BLOG_HOST/blog/all" |
		grep '<span class="date">' |
		sed -n 's/.*href="\/\([^"]*\).*$/\1/p'
)

index=1
for entry in $entries; do
	if wkhtmltopdf "${BLOG_HOST}/${entry}" "${index}.pdf" >/dev/null; then
		index=$((index + 1))
	fi
done

pdfunite $(find -- *pdf | grep -v "$OUTPUT_FILE" | sort -nr | xargs) "../$OUTPUT_FILE"
