#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Interacts with console and
# logs from Heroku cli
#
# Requires:
#   - heroku
#   - slc
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
# ----------------------- vars
APPS_FILE="${HOME}/.herokuappstemp"
DYNOS_FILE="${HOME}/.herokudynostemp"
#-----------------------------

USAGE="USAGE: hkc [ACTION]

OUTPUT
  l, logs     Heroku logs
  c, console  Heroku console
  h, help     Print this guide"
print_usage() { echo "$USAGE"; }

select_app() {
	if [ ! -f "$APPS_FILE" ]; then
		heroku apps | tail -n +2 | head -n -1 >"$APPS_FILE"
	fi

	if selected="$(slc <"$APPS_FILE")"; then
		echo "$selected"
	else
		exit 1
	fi
}

select_dyno() {
	heroku ps --app="$1" | grep '===' | grep -v run | sed 's/=== \([a-z]\+\).*/\1/' >"$DYNOS_FILE"

	if selected="$(slc <"$DYNOS_FILE")"; then
		echo "$selected"
	else
		rm .herokudynostemp
		exit 1
	fi
}

hkc_logs() {
	app="$(select_app)"
	dyno="$(select_dyno "$app")"

	heroku logs -t --app="${app}" --dyno="${dyno}"
}

hkc_console() {
	if app="$(select_app)"; then
		heroku run console --app="${app}"
	fi
}

case "$1" in
l | logs) hkc_logs ;;
c | console) hkc_console ;;
*) print_usage ;;
esac
