#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily send predefined
# notifications
#
# Requires:
#   - slc (custom)
#   - notify-send
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#-----------------------------

USAGE="Usage: nfy [NOTIFICATION]

Notification
  -         Enter interactive mode
  d, date   Notify curent datetime
  h, help   Print this help"
print_usage() { echo "$USAGE"; }

notify_date() { notify-send -t 10000 "date" "$(date)"; }
custom_notification() { notify-send "$@"; }

if [ -z "$1" ]; then
	notifications="date"
	if notification="$(echo "$notifications" | slc)"; then
		nfy "$notification"
		exit "$?"
	else
		exit 1
	fi
fi

case "$1" in
d | date) notify_date ;;
h | help) print_usage ;;
*) custom_notification "$@" ;;
esac
