#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
#
# Requires:
#   - yay
#   - nsl (custom)
#   - ntf (custom)
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
DEPS=
#-----------------------------

USAGE="Usage: ppp [ACTION] [SCRIPT]

Action
  -                         Enter interactive mode
  i, install [SCRIPT...]    Install scripts provided. All if none specified.
  u, uninstall [SCRIPT...]  Uninstall scripts provided. All if none specified.
  h, help                   Print this help"
print_usage() { echo "$USAGE"; }

defdeps() { DEPS="$DEPS $*"; }

if [ -z "$1" ]; then
	if action="$(nsl install uninstall)"; then
		ppp "$action"
		exit "$?"
	else
		exit 1
	fi
fi

ACTION="$1"
shift

SCRIPTS="${*:-tdo sux sxt blk rrr skb nfy wal lok dkr slc nsl xpl pmo dkc fch}"
for script in $SCRIPTS; do
	case $script in
	sux) defdeps polkit ;;
	skb) defdeps xorg-setxkbmap ;;
	nfy) defdeps notify-send.sh ;;
	wal) defdeps hsetroot ;;
	lok) defdeps i3lock-color ;;
	slc) defdeps fzf dmenu ;;
	xpl) defdeps zathura zathura-pdf-mupdf ;;
	dkc) defdeps jq ;;
	esac
done
DEPS="$(echo "$DEPS" | tr ' ' '\n' | sort -u | xargs)"

case "$ACTION" in
i | install) yay -S $DEPS ;;
u | uninstall) yay -R $DEPS ;;
h | help) print_usage ;;
esac
