#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily list and run scripts
#
# Requires:
#   - slc (custom)
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
SCRIPTS="$HOME/sh"
#-----------------------------

USAGE="Usage: rrr

Script
  -         Enter interactive mode
  h, help   Print this help"
print_usage() { echo "$USAGE"; }

if [ -z "$1" ]; then
	if script="$(find "$SCRIPTS"/* -type f -executable -printf '%f\n' | grep -E '^[a-z]{3}$' | slc)"; then
		"$script"
		exit "$?"
	else
		exit 1
	fi
else
	print_usage
fi
