#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily list and run scripts
#
# Requires:
#   - slc (custom)
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
SCRIPTS="$HOME/sh"
#-----------------------------

USAGE="Usage: rrr

Script
  -         Enter interactive mode
  h, help   Print this help"
print_usage() { echo "$USAGE"; }

options="arandr
block pages
docker
edit configs
keyboard layout
swicth theme
system exit
todo
wallpapers
pick color
explain man"

if selection="$(echo "$options" | slc)"; then
	case "$selection" in
	"arandr") adr ;;
	"block pages") blk ;;
	"docker") dkr ;;
	"edit configs") edt ;;
	"keyboard layout") skb ;;
	"swicth theme") swc ;;
	"system exit") sxt ;;
	"todo") tdo ;;
	"wallpapers") wal ;;
	"pick color") xcl ;;
	"explain man") xpl ;;
	*) exit 1 ;;
	esac
else
	exit 1
fi
