#!/usr/bin/env sh

##############################
# @jaimecgomezz
#
# Easily list and run scripts
#
# Requires:
#   - fzf
##############################

SCRIPTS="$HOME/sh"

USAGE="Usage: rrr [Script]

Script
  *         Any valid script
  -         Enter interactive mode
  h, help   Print this help"
print_usage() { echo "$USAGE"; }

if [ -z "$1" ]; then
	if script="$(find "$SCRIPTS"/* -type f -executable -printf '%f\n' | fzf)"; then
		rrr "$script"
		exit "$?"
	else
		exit 1
	fi
fi

case "$1" in
h | help) print_usage ;;
esac

"$1"
exit "$?"
