#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Select interactively based
# on context
#
# Requires:
#   - fzf
#   - dmenu
#------------------- protected
PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
FZF="${FZF:-fzf}"
DMENU="${DMENU:-dmenu}"
#-----------------------------

USAGE="Usage: slc [ARG...]

Arg
  Any parameter is forwarded to the selector"
print_usage() { echo "$USAGE"; }

case "$PNAME" in
i3 | systemd) $DMENU "$@" ;;
*) $FZF ;;
esac
