#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Select interactively based
# on context
#
# Requires:
#   - fzf
#   - dmenu
#------------------------ vars
FZF="${FZF:-fzf}"
DMENU="${DMENU:-dmenu}"
#-----------------------------

USAGE="Usage: slc PARENT [ARG...]

Parent
  systemd   Triggers dmenu selector
  *         Triggers fzf selector"
print_usage() { echo "$USAGE"; }

PARENT="$1"
shift

case "$PARENT" in
systemd) $DMENU "$@" ;;
*) $FZF "$@" ;;
esac
