#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Run commands as sudo
#
# Requires:
#   - polkit
#-----------------------------

activate_agent() { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 2>/dev/null & }

activate_agent || activate_agent

pkexec sh -c "$@"

exit "$?"
