#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily colorschemes across
# the OS
#
# Requires:
#   - slc (custom script)
#   - nfy (custom script)
#   - xclip
#   - spicetify
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#-----------------------------

USAGE="USAGE: swc [COLORSCHEME]

COLORSCHEME
  nord,horizon,paradise"
print_usage() { echo "$USAGE"; }

options="nord
horizon
paradise"

set_xresource() { sed -i "s/.*theme.*/#include \".Xresources.d\/${1}\" \/\* theme \*\//g" "$HOME/.Xresources"; }
set_fzf() { sed -i "s/^source.*fzf.*/source \"\$HOME\/.config\/fzf\/${1}.config\"/g" "$HOME/.bashrc"; }
set_rofi() { sed -i "s/@theme.*/@theme \"${1}.rasi\"/g" "$HOME/.config/rofi/config.rasi"; }
set_kitty() { sed -i "s/^include.*/include ${1}.conf/g" "$HOME/.config/kitty/kitty.conf"; }
set_zathura() { sed -i "s/^include.*/include ${1}/g" "$HOME/.config/zathura/zathurarc"; }
set_bat() { sed -i "s/^--theme.*/--theme=\"${1}\"/g" "$HOME/.config/bat/config"; }
set_lok() { sed -i "s/\(.*\)--color=.*/\1--color=\"${1}\" \\\/g" "$HOME/sh/lok"; }
set_nvim() {
	sed -i "s/^.*theme =.*/local theme = \"${1}\"/g" "$HOME/.config/nvim/lua/colors.lua"
	sed -i "s/\(.*\)theme =.*/\1theme = \"${2}\" --/g" "$HOME/.config/nvim/lua/plugins/lualine.lua"
}
set_spotify() {
	spicetify config current_theme "$1"
	spicetify config color_scheme "$2"
	spicetify apply
}
set_slack() { echo "$1" | xclip -selection c; }
set_insomnia() { nfy -u "critical" "Insomnia theme: ${1}"; }
set_i3() {
	sed -i \
		-e "s/\(.*\)\(client.focused.*\)/# \2/" \
		-e "s/\(.*\)\(client.focused.*\)# ""$1""/\2 # ""$1""/" \
		"$HOME/.config/i3/config"
}
set_bash() { sed -i "s/\(export THEME\=\).*/\1""$1""/" "$HOME/.bashrc"; }

set_nord() {
	set_bash "nord"
	set_xresource "nord"
	set_nvim "nord" "nord"
	set_rofi "nord"
	set_kitty "nord"
	set_zathura "nord"
	set_spotify "Sleek" "Cherry"
	set_fzf "nord"
	set_bat "Nord"
	set_lok "2E3440"
	set_slack "#2E3440,#3B4252,#88C0D0,#2E3440,#3B4252,#D8DEE9,#A3BE8C,#81A1C1"
	set_insomnia "insomnia-plugin-theme-nord"
	set_i3 "nord"
	wal "$HOME/pictures/walls/nord/light-drowing.jpg"
}

set_paradise() {
	set_bash "paradise"
	set_xresource "paradise"
	set_nvim "paradise" "auto"
	set_rofi "paradise"
	set_kitty "paradise"
	set_zathura "paradise"
	set_spotify "Ziro" "gray-dark"
	set_fzf "paradise"
	set_bat "base16"
	set_lok "151515"
	set_slack "#1D2229,#0B161E,#537AA6,#FFFFFF,#313843,#FFFFFF,#94E864,#78AF8F,#0B161E,#FFFFFF"
	set_insomnia "One Dark"
	set_i3 "paradise"
	wal "$HOME/pictures/walls/dark/b-565.png"
}

set_horizon() {
	set_bash "horizon"
	set_xresource "horizon"
	set_nvim "horizon" "auto"
	set_rofi "horizon"
	set_kitty "horizon"
	set_zathura "horizon"
	set_spotify "Sleek" "Horizon"
	set_fzf "horizon"
	set_bat "base16"
	set_lok "1C1E26"
	set_slack "#232530,#101010,#FAB28E,#1C1E26,#E95379,#FDF0ED,#F43E5C,#E9436F,#F43E5C,#16161C"
	set_insomnia "One Dark"
	wal "$HOME/pictures/walls/blood/b-380.png"
}

theme="$1"

if [ -z "$theme" ]; then
	if ! theme="$(echo "$options" | slc)"; then
		exit 1
	fi
fi

case "$theme" in
nord) set_nord ;;
paradise) set_paradise ;;
horizon) set_horizon ;;
*) print_usage ;;
esac
