#!/usr/bin/env sh

##############################
# @jaimecgomezz
#
# Simple todo list
#
# Requires:
#   - fzf
##############################

TASKS="$HOME/tasks"

USAGE="Usage: tdo [Task]
TASK
  -         Enter interactive mode
  [Task]    Add/delete task
  h, help   Print this help"
print_usage() { echo "$USAGE"; }

handle_task() {
	TASK="$*"
	if grep "^${TASK}$" <"$TASKS"; then
		for e in $TASK; do
			sed -i "\|${e}|d" "$TASKS"
		done
	else
		echo "$TASK" >>"$TASKS"
		sed -i -e '/^$/d' -e '/^ *$/d' "$TASKS"
	fi

	tdo
}

if [ -z "$1" ]; then
	task="$(fzf --print-query <"$TASKS" | tr -d '\n')"
	[ -n "$task" ] || exit 1
	tdo "$task"
	exit 0
fi

case "$1" in
h | help) print_usage ;;
*) handle_task "$@" ;;
esac
