#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily switch wallpapers
#
# Requires:
#   - slc (custom script)
#   - hsetroot
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
THEME="${1:-$THEME}"
WALLPAPERS="${HOME}/pictures/walls"
SYMBOLIC="${HOME}/pictures/wallpaper"
#-----------------------------

USAGE="Usage: wal [THEME] [WALLPAPER]

Theme
  -             Enter themes interactive mode
  [THEME]       Any folder under the WALLPAPERS folder
  h, help       Print this help

Wallpaper
  -             Enter wallpapers interactive mode
  [WALLPAPER]   Any image under the WALLPAPERS/[Theme] folder"
print_usage() { echo "$USAGE"; }

set_wal() {
	rm "$SYMBOLIC"
	ln -s "$1" "$SYMBOLIC"
	hsetroot -cover "$SYMBOLIC" >/dev/null
}

# Translate theme to wallpaper folder when they dont match
case "$THEME" in
horizon) THEME=blood ;;
paradise) THEME=dark ;;
esac

# If first argyment is a valid file, set it as wallpaper
if [ -r "$THEME" ]; then
	set_wal "$THEME"
	exit $?
# Look for wallpapers within the selected theme and, if second argument is
# provided is assumed to be a previously selected wallpaper so we can continue
# exploring wallpapers from that point on
elif wallpaper="$(find "$WALLPAPERS/$THEME"/* -maxdepth 1 -type f -printf '%f\n' | slc -select "$2")"; then
	set_wal "$WALLPAPERS/$THEME/$wallpaper"
	wal "$THEME" "$wallpaper"
else
	exit 1
fi
