#!/usr/bin/env sh

#-----------------------------
# @jaimecgomezz
#
# Easily switch wallpapers
#
# Requires:
#   - slc (custom script)
#   - hsetroot
#------------------- protected
export PNAME="${PNAME:-$(ps --no-headers -o comm $PPID)}"
#------------------------ vars
WALLPAPERS="${HOME}/pictures/walls"
#-----------------------------

USAGE="Usage: wal [Theme] [Wallpaper]

Theme
  -             Enter themes interactive mode
  [Theme]       Any folder under the WALLPAPERS folder
  h, help       Print this help

Wallpaper
  -             Enter wallpapers interactive mode
  [Wallpaper]   Any image under the WALLPAPERS/[Theme] folder"
print_usage() { echo "$USAGE"; }

set_wal() { hsetroot -cover "$WALLPAPERS/$1/$2" >/dev/null; }

if [ -z "$1" ]; then
	if theme="$(find "$WALLPAPERS"/* -maxdepth 1 -type d -printf '%f\n' | slc "$PNAME")"; then
		wal "$theme"
		exit "$?"
	else
		exit 1
	fi
else
	theme="$1"
	if [ -z "$2" ]; then
		if wal="$(find "$WALLPAPERS/$theme"/* -maxdepth 1 -type f -printf '%f\n' | slc "$PNAME")"; then
			set_wal "$theme" "$wal"
		else
			exit 1
		fi
	else
		set_wal "$theme" "$2"
	fi
fi
